---
sudo: required
services:
- docker
language: node_js
node_js:
- 'node'
env:
  global:
  - GH_REF: github.com/chad-autry/wac-prometheus
script:
- docker build -t chadautry/wac-prometheus:latest .
- if [[ ! -z "$TRAVIS_TAG" ]]; then docker tag chadautry/wac-prometheus:latest chadautry/wac-prometheus:$TRAVIS_TAG ; fi
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push chadautry/wac-prometheus
